apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  ## relicaset lables
  labels:
    purpose: ingress-service
    project: roboshop
    name: app1
spec:
  replicas: 4
  selector:
  ## these lables are used to select the pods
    matchLabels:
      purpose: ingress-service
      project: roboshop
      name: app1
  ## pod definition
  template:
    metadata:
      labels:
        purpose: dp-service
        project: roboshop
        name: app1
    spec:
      containers:
      - name: app1
        image: rajmdevops/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  lables:
    purpose: dp-service
    project: roboshop
    name: app1
spec:
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/listen-ports:  '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:848332098195:certificate/e8bd18f7-4b77-4476-bce6-ac4510448bca
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb 
  rules:
  - host: "app1.rajkumardaws.space"
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: app1
            port:
              number: 80
 
