apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  ## relicaset lables
  labels:
    purpose: ingress-service
    project: roboshop
    name: app2
spec:
  replicas: 4
  selector:
  ## these lables are used to select the pods
    matchLabels:
      purpose: ingress-service
      project: roboshop
      name: app2
  ## pod definition
  template:
    metadata:
      labels:
        purpose: ingress-service
        project: roboshop
        name: app2
    spec:
      containers:
      - name: app2
        image: rajmdevops/app2:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    purpose: ingress-service
    project: roboshop
    name: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    alb.ingress.kubernetes.io/listen-ports:  '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:848332098195:certificate/57702002-88ad-4432-8805-45b3a27ea30c
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb 
  rules:
  - host: "app2.rajkumardaws.space"
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: app2
            port:
              number: 80
 
